src/Entity/Tareas.php
<?php

namespace App\Entity;

use App\Repository\TareasRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TareasRepository::class)]
class Tareas
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titulo = null;

    #[ORM\Column(length: 255)]
    private ?string $descripcion = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fecha_creacion = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fecha_vencimiento = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getFechaCreacion(): ?\DateTimeInterface
    {
        return $this->fecha_creacion;
    }

    public function setFechaCreacion(\DateTimeInterface $fecha_creacion): self
    {
        $this->fecha_creacion = $fecha_creacion;

        return $this;
    }

    public function getFechaVencimiento(): ?\DateTimeInterface
    {
        return $this->fecha_vencimiento;
    }

    public function setFechaVencimiento(\DateTimeInterface $fecha_vencimiento): self
    {
        $this->fecha_vencimiento = $fecha_vencimiento;

        return $this;
    }
}

src/Form/TareasType.php
<?php

namespace App\Form;

use App\Entity\Tareas;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TareasType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titulo')
            ->add('descripcion')
            ->add('fecha_creacion')
            ->add('fecha_vencimiento')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tareas::class,
        ]);
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    #[Route('/', name: 'app_main')]
    public function index(): Response
    {
        return $this->render('main/index.html.twig', [
            'controller_name' => 'MainController',
        ]);
    }
}

src/Controller/TareasController.php
<?php

namespace App\Controller;

use App\Entity\Tareas;
use App\Form\TareasType;
use App\Repository\TareasRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/tareas')]
class TareasController extends AbstractController
{
    #[Route('/', name: 'app_tareas_index', methods: ['GET'])]
    public function index(TareasRepository $tareasRepository): Response
    {
        return $this->render('tareas/index.html.twig', [
            'tareas' => $tareasRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_tareas_new', methods: ['GET', 'POST'])]
    public function new(Request $request, TareasRepository $tareasRepository): Response
    {
        $tarea = new Tareas();
        $form = $this->createForm(TareasType::class, $tarea);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $tareasRepository->save($tarea, true);

            return $this->redirectToRoute('app_tareas_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('tareas/new.html.twig', [
            'tarea' => $tarea,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tareas_show', methods: ['GET'])]
    public function show(Tareas $tarea): Response
    {
        return $this->render('tareas/show.html.twig', [
            'tarea' => $tarea,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_tareas_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Tareas $tarea, TareasRepository $tareasRepository): Response
    {
        $form = $this->createForm(TareasType::class, $tarea);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $tareasRepository->save($tarea, true);

            return $this->redirectToRoute('app_tareas_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('tareas/edit.html.twig', [
            'tarea' => $tarea,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tareas_delete', methods: ['POST'])]
    public function delete(Request $request, Tareas $tarea, TareasRepository $tareasRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tarea->getId(), $request->request->get('_token'))) {
            $tareasRepository->remove($tarea, true);
        }

        return $this->redirectToRoute('app_tareas_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/redon/Desktop/florida/servidor/AP7/AP7/src/Controller/MainController.php'|file_link(0) }}">src/Controller/MainController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/redon/Desktop/florida/servidor/AP7/AP7/templates/main/index.html.twig'|file_link(0) }}">templates/main/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/tareas/_delete_form.html.twig
<form method="post" action="{{ path('app_tareas_delete', {'id': tarea.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tarea.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tareas/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/tareas/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Tareas{% endblock %}

{% block body %}
    <h1>Edit Tareas</h1>

    {{ include('tareas/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_tareas_index') }}">back to list</a>

    {{ include('tareas/_delete_form.html.twig') }}
{% endblock %}

templates/tareas/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tareas index{% endblock %}

{% block body %}
    <h1>Tareas index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titulo</th>
                <th>Descripcion</th>
                <th>Fecha_creacion</th>
                <th>Fecha_vencimiento</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for tarea in tareas %}
            <tr>
                <td>{{ tarea.id }}</td>
                <td>{{ tarea.titulo }}</td>
                <td>{{ tarea.descripcion }}</td>
                <td>{{ tarea.fechaCreacion ? tarea.fechaCreacion|date('Y-m-d') : '' }}</td>
                <td>{{ tarea.fechaVencimiento ? tarea.fechaVencimiento|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_tareas_show', {'id': tarea.id}) }}">show</a>
                    <a href="{{ path('app_tareas_edit', {'id': tarea.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_tareas_new') }}">Create new</a>
{% endblock %}

templates/tareas/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Tareas{% endblock %}

{% block body %}
    <h1>Create new Tareas</h1>

    {{ include('tareas/_form.html.twig') }}

    <a href="{{ path('app_tareas_index') }}">back to list</a>
{% endblock %}

templates/tareas/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tareas{% endblock %}

{% block body %}
    <h1>Tareas</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ tarea.id }}</td>
            </tr>
            <tr>
                <th>Titulo</th>
                <td>{{ tarea.titulo }}</td>
            </tr>
            <tr>
                <th>Descripcion</th>
                <td>{{ tarea.descripcion }}</td>
            </tr>
            <tr>
                <th>Fecha_creacion</th>
                <td>{{ tarea.fechaCreacion ? tarea.fechaCreacion|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Fecha_vencimiento</th>
                <td>{{ tarea.fechaVencimiento ? tarea.fechaVencimiento|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_tareas_index') }}">back to list</a>

    <a href="{{ path('app_tareas_edit', {'id': tarea.id}) }}">edit</a>

    {{ include('tareas/_delete_form.html.twig') }}
{% endblock %}